### ISSUE TITLE
请问，如何训练自己的3D点云数据？

### ISSUE THREAD

**Issue by electronicYH** [WeijingShi/Point-GNN#1]
你好，我手头有些自己的3D点云数据，想请问，有什么方式，我可以直接把我的3D点云数据用来训练，而不用经过KITTI的数据格式转换？很急，请求帮助！

**Comment by WeijingShi** [comment]
For training using a custom dataset, the easiest way is to create a data loader. The data loader needs to provide points and labels.  Please refer to the example [kitti_dataset.py](../blob/master/dataset/kitti_dataset.py).
