### ISSUE TITLE
IN Inference,  the checkpoint can test directly?

### ISSUE THREAD

**Issue by FireflyInwater** [WeijingShi/Point-GNN#13]
as title says

**Comment by WeijingShi** [comment]
If you are wondering whether the eval.py script can generate mAP directly, the current eval.py does not. But you can use the run.py to do inference from a checkpoint, and test its results' mAP using the evaluate_object_offline tool.

**Comment by FireflyInwater** [comment]
> 如果您想知道eval.py脚本是否可以直接生成mAP，则当前的eval.py不能。但是，您可以使用run.py从检查点进行推断，并使用Evaluation_object_offline工具测试其结果的mAP。

thanks!
