### ISSUE TITLE
Visualizing 3D Bounding Box on Point Cloud

### ISSUE THREAD

**Issue by amritpaul** [WeijingShi/Point-GNN#14]
Hi,
Thanks a lot for providing the codebase. I have trained it and the results look pretty good as described in the paper. However, I wasn't able to figure out how to plot the predicted 3D bounding boxes on the point cloud. Can anyone help me resolve this issue?

**Comment by WeijingShi** [comment]
The run.py script contains a flag **--level LEVEL** to turn on some visualizations. 

For example:
```
python3 run.py checkpoints/car_auto_T3_trainval/ --level 1 --test --dataset_root_dir DATASET_ROOT_DIR --output_dir DIR_TO_SAVE_RESULTS
```
This will enable a 3D view visualization with the boxes plotted. You can press [q] for the next frame.
For consecutive visualization of without blocking the code, you can set **--level 2**. 

I hope it helps.
