### ISSUE TITLE
Inference doesnt work continously.. why??

### ISSUE THREAD

**Issue by MohamedAboushnief** [WeijingShi/Point-GNN#16]
I use this command `python3 run.py checkpoints/car_auto_T3_trainval/ --level 2 --test  --output_dir DIR_TO_SAVE_RESULTS` to visualize. But when I run it it only views the first image file and velodyne file only and doesnt continue. and when i press ( q ) as mentioned it terminates.

**Comment by WeijingShi** [comment]
Can you provide more info from the terminal?

**Comment by WeijingShi** [comment]
Closed due to lack of activity.
