### ISSUE TITLE
Visualize 3D coordinates and 2D coordinates？

### ISSUE THREAD

**Issue by swzaaaaaaa** [WeijingShi/Point-GNN#19]
Excuse me, during the test, 2D coordinates and 3D coordinates will be output. How to draw 2D coordinates and 3D coordinates into the test picture? May I ask, do you have relevant videos and detailed blogs about your paper?Thank you.

**Comment by WeijingShi** [comment]
Hi, the run.py script can visualize both 2D and 3D bounding box if the argument --level is specified. 
--level=1 for nonblocking visualization and --level=2 for blocking visualization. You can also build your custom visualization by using the coordinates in output files.  

We have put the details in our Point-GNN paper: https://arxiv.org/abs/2003.01251. At this moment, we don't have a blog or video.
Thanks,
