### ISSUE TITLE
Questions regarding the naming of files

### ISSUE THREAD

**Issue by dirk61** [WeijingShi/Point-GNN#2]
First of all, I really like the work you've done! Good job!😀

I'm quite confused about the "T0"~"T3" and the combination of "train" and "eval" in some of the file names. For example, in the configs/ directory, what's the difference between car_auto_T0_train_config & car_auto_T3_train_config & car_auto_T3_train_train_config? It would be really helpfu if I can understand how you name these files!😀
<img width="389" alt="2020315-91139" src="https://user-images.githubusercontent.com/54100411/76693260-25e6c200-669d-11ea-8009-ad9a1d3cfb51.png">

**Comment by WeijingShi** [comment]
The checkpoints are named after the ablation study we did in the paper. 

In general, the name follows [Class type] + [Use auto-registration (auto) or not (fixed)] + [Number of layers] + [data split file] + [config/train_config/eval_config]. 

For example, _car_auto_T3_train_train_config_ means: a train_config file, using T=3 layers, each layer use auto-registration, trained on the KITTI train split.  

I hope this helps to clear the confusion.
