### ISSUE TITLE
How to split the data ?

### ISSUE THREAD

**Issue by cuge1995** [WeijingShi/Point-GNN#21]
the original 
.
├── testing
│   ├── calib
│   ├── det_2
│   ├── image_2
│   ├── image_3
│   ├── prev_2
│   ├── prev_3
│   └── velodyne
└── training
    ├── calib
    ├── det_2
    ├── image_2
    ├── image_3
    ├── label_2
    ├── prev_2
    ├── prev_3
    └── velodyne

**Comment by WeijingShi** [comment]
Can you elaborate on your question?

**Comment by cuge1995** [comment]
the dataset I download from KITTI and unzip it, the tree structure of the file is as above.

**Comment by WeijingShi** [comment]
By default, we recommend the following file structure. For the details, please refer to [README](https://github.com/WeijingShi/Point-GNN/blob/master/README.md)

    DATASET_ROOT_DIR
    ├── image                    #  Left color images
    │   ├── training
    |   |   └── image_2            
    │   └── testing
    |       └── image_2 
    ├── velodyne                 # Velodyne point cloud files
    │   ├── training
    |   |   └── velodyne            
    │   └── testing
    |       └── velodyne 
    ├── calib                    # Calibration files
    │   ├── training
    |   |   └──calib            
    │   └── testing
    |       └── calib 
    ├── labels                   # Training labels
    │   └── training
    |       └── label_2
    └── 3DOP_splits              # split files.
        ├── train.txt
        ├── train_car.txt
        └── ...
