### ISSUE TITLE
Provide me  file of train_config_path and config_path for training the model

### ISSUE THREAD

**Issue by merazlab** [WeijingShi/Point-GNN#22]
## Trainning

`usage: train.py [-h] [--dataset_root_dir DATASET_ROOT_DIR]
                [--dataset_split_file DATASET_SPLIT_FILE]
                train_config_path config_path`

**Comment by WeijingShi** [comment]
Hi, All train_config and config files are in the folder [configs/](https://github.com/WeijingShi/Point-GNN/tree/master/configs)

For example, to train a model of three layers on the train split:
```
python3 train.py configs/car_auto_T3_train_train_config configs/car_auto_T3_train_config
```

For more on the naming conventions, please refer [here](https://github.com/WeijingShi/Point-GNN/issues/17#issuecomment-640109341)

Thanks,
