### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by 14212094** [WeijingShi/Point-GNN#26]
Thank you for you great job!
I follow the file structure of you，like this：
![pognn2](https://user-images.githubusercontent.com/38451498/86305282-db855300-bc43-11ea-9b28-1ce1f0c1b365.png)

When i run this command:
python3 run.py checkpoints/car_auto_T3_train/ --dataset_root_dir /home/lwy/Point-GNN/dataset/kitti --output_dir /home/lwy/Point-GNN/results
I get this error
![pognn](https://user-images.githubusercontent.com/38451498/86305342-04a5e380-bc44-11ea-92c6-2ef6cfd15210.png)
I am a newer of Python.How can i fix it?Thank you

**Comment by WeijingShi** [comment]
Hi @14212094, Thank you for your interest. You need to put the 3DOP split files in the 3DOP_splits folder. You can download them from here: https://xiaozhichen.github.io/files/mv3d/imagesets.tar.gz

**Comment by 14212094** [comment]
@WeijingShi Thank you so much.I put the wrong files in the 3DOP_splits folder,and the labels file is needed.The problem is solved.
