### ISSUE TITLE
Pedestrian & Cyclist Config

### ISSUE THREAD

**Issue by Divadi** [WeijingShi/Point-GNN#28]
Hi, I had a couple questions on the released config for ped & cyc

Here, why is the voxelization size 0.8? I remember in the paper it said 0.4 for training and 0.2 for testing.
https://github.com/WeijingShi/Point-GNN/blob/2baf24f9556907f23e2e4018f1b756dac3f6c497/configs/ped_cyl_auto_T3_trainval_config#L7

Also here, it seems like it trains on the entire trainval split instead of just train. For validation on val split, we should only train on the train split, right?
https://github.com/WeijingShi/Point-GNN/blob/2baf24f9556907f23e2e4018f1b756dac3f6c497/configs/ped_cyl_auto_T3_trainval_train_config#L60

**Comment by WeijingShi** [comment]
Hi @Divadi, Thanks for your interest. 

The voxel size is "base_voxel_size" multiplied by "graph_scale". For example, base_voxel_size=0.8 and graph_scale=0.5 means a voxel of size 0.4. 

https://github.com/WeijingShi/Point-GNN/blob/2baf24f9556907f23e2e4018f1b756dac3f6c497/models/graph_gen.py#L26

The ped_cyl_auto_T3_trainval_train_config trains the model for the test set. Yes, if you want to evaluate on the val split, you need to exclude the val split and use train split.

Hope this helps.
