### ISSUE TITLE
The lines of the output and field of view

### ISSUE THREAD

**Issue by Juuustin** [WeijingShi/Point-GNN#29]
There are two small questions in terms of the output and field of view.

The first one is that when I check the output in the open3D, I found that there are several radials from the center of the box to the ground, I am confused by the meaning of those radials.

The second one is the field of view for detection, that is, what is the degree of the region.

Looking forward to hearing from you soon!

**Comment by WeijingShi** [comment]
Hi @Juuustin 

The "radials" are graph edges between the output point and its neighbors. 

In KITTI, only the objects within the front camera are labeled. We remove the points outside the image. The remaining region within about  [-40, 40] degree. 

Thanks,

**Comment by Juuustin** [comment]
Hi, @WeijingShi 

Thank you for your reply. I am still confused about the 'radials', there is an example of my output:
![New Microsoft PowerPoint Presentation](https://user-images.githubusercontent.com/49072829/89195588-3eeb0380-d5a9-11ea-9f11-8044268809cd.jpg)

As we can see, there are plenty of red 'radials' connecting Lidar point clouds with the bounding box, it would be better if there is more explanation based on the example. 

I am looking forward to hearing from you soon!

Best Wishes!

**Comment by WeijingShi** [comment]
Hi @Juuustin, In this example, the pink points are the downsampled point cloud. We construct a graph by connecting those pink points to each other.  Each pink point is classified and might output a bounding box.  During post-processing, we will select one point per object to get the bounding box. The "radius" are the connections between this selected point to other neighborhood pink points. If you zoom in and make the points small by press the "-" key (between "0" key and "=" key), you can see a more clear picture. We didn't visualize the complete graph as it will be messy. Therefore, we only visualize the edges connecting the output points for debugging purposes.  Thanks,

**Comment by Juuustin** [comment]
Hi @WeijingShi, thank you for the clear explanation, and I will close this issue now
