### ISSUE TITLE
Evaluation not working

### ISSUE THREAD

**Issue by dirk61** [WeijingShi/Point-GNN#3]
I ran the eval.py following your guidance but it seems something's gone wrong.
<img width="366" alt="微信图片_20200315101453" src="https://user-images.githubusercontent.com/54100411/76693775-db1d7800-66a5-11ea-8842-2777e92646b1.png">
It gives me this Index out of range error, have I done something wrong?
<img width="409" alt="微信图片_20200315101459" src="https://user-images.githubusercontent.com/54100411/76693776-dce73b80-66a5-11ea-98c6-a39a4e615714.png">

**Comment by WeijingShi** [comment]
It's caused by a mismatch between the split file and eval_config. In eval_config, NUM_TEST_SAMPLE is set to be the same as the _val_ split, while you are using _train_car_ split. 

I've updated the train_config and eval_config to set NUM_TEST_SAMPLE from the split file. It should be fine now.

**Comment by dirk61** [comment]
@WeijingShi Thanks! It works.
