### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by 14212094** [WeijingShi/Point-GNN#31]
Hi!
I try to train the the model
But I get this error,how can i fix it?Thank you so much!
/home/lwy/图片/ttt.png

My command is :
python3 train.py --dataset_root_dir /home/lwy/Point-GNN/dataset/kitti --dataset_split_file /home/lwy/Point-GNN/dataset/kitti/3DOP_splits/train_car.txt configs/car_auto_T3_train_train_config configs/car_auto_T3_train_config
I had configured the parameters of two config files.
Is there any wrong?

**Comment by WeijingShi** [comment]
Hi @14212094, The image (a screenshot I presume) did not show up in your post. Can you provide more error info from the terminal?
