### ISSUE TITLE
Should val be added to the training when submitted on the official website?

### ISSUE THREAD

**Issue by LittleYuanzi** [WeijingShi/Point-GNN#32]
Hello, do you need to add the val dataset to the training to submit your results on the KITTI official website? I did so, but the accuracy decreased by 3 percentage points. Can you tell me the reason for this?

**Comment by WeijingShi** [comment]
Hi @LittleYuanzi, the val split is almost 50% of the total KITTI training data. Adding the val split to the training dataset should give you an edge on the testing results. Did you train the model using (train split + val split) and got worse test results than training with (train split) alone?  What training configuration did you use?  Thanks,
