### ISSUE TITLE
problem when training

### ISSUE THREAD

**Issue by xiaoyuSui** [WeijingShi/Point-GNN#38]
There is an error when training:

RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

I searched online and it says this is because I am running in Windows and multi-thread program(the data loading part)should be inside  if __name__ == '__main__': .I tried hard but once I change a bit there comes more errors. I really can not fix it because I am such a new starter OTZ. Please help!

**Comment by WeijingShi** [comment]
Hi @xiaoyuSui , It seems that in Windows the new process will import the main. Could you try to insert 
```
if __nam__ == '__main__':  
```
to prevent code after the following line to execute? https://github.com/WeijingShi/Point-GNN/blob/2baf24f9556907f23e2e4018f1b756dac3f6c497/train.py#L172
Let me know if this works. Thanks,

**Comment by xiaoyuSui** [comment]
Thank you sooooo much! It works! It is so nice of you to help me out! Actually I have tried it before but now it seems I got some other things wrong then

**Comment by typhoonlee** [comment]
Hi,Where did you insert this line of code? I am facing the same problem now, looking forward to your reply
@xiaoyuSui

**Comment by xiaoyuSui** [comment]
I remember it should have worked.

if __name__ == '__main__':
    # model =======================================================================
    if 'COPY_PER_GPU' in train_config:
        COPY_PER_GPU = train_config['COPY_PER_GPU']
    else:
        COPY_PER_GPU = 1
    NUM_GPU = train_config['NUM_GPU']
