### ISSUE TITLE
The 3DOP train/val split is unavailable

### ISSUE THREAD

**Issue by FantineFu** [WeijingShi/Point-GNN#39]
It seems that the address of 3DOP train/val split you provided is unavailable, the author may remove it. Could you kindly please add them in git directly?

**Comment by WeijingShi** [comment]
Hi @FantineFu , the link seems to work, could you try it again? https://xiaozhichen.github.io/files/mv3d/imagesets.tar.gz

**Comment by FantineFu** [comment]
It works now. Thanks~

**Comment by WeijingShi** [comment]
Great!
