### ISSUE TITLE
Why train the code so slow?

### ISSUE THREAD

**Issue by happinesslz** [WeijingShi/Point-GNN#4]
Thanks for your nice code.  I use  tensorflow-gpu==1.15.0 to train your code on single Titan Xp GPU, but the GPU is occupied on 0%  and the memory usage is only 158M?  In addition, on GTX 1070,  I also meet the same problem.  Can you explain why? Thanks. 

I follow your README and run the following command (for single gpu, and I also  reduce the batch size and NUM_GPU):
`CUDA_VISIBLE_DEVICES=7 python train.py configs/car_auto_T3_train_train_config configs/car_auto_T2_train_config`

**Comment by WeijingShi** [comment]
Could you check if the process is still running on the CPU side? In the current training code, the 1st epoch is slower as the dataloader loads the data the first time. It might take several minutes before the training on the GPU start.  
Also, the training on _train_ split takes around 9GB memory space, if the system runs out of memory, it might be swapping the memory to disk, which might slow down things a lot.

**Comment by happinesslz** [comment]
@WeijingShi  
![image](https://user-images.githubusercontent.com/40748327/77384734-195f1980-6dc1-11ea-9ba4-fcaa1ef8262e.png)
 The time cost is too long. I use your default settings and train the model by  two GPUs with batch_size=4
