### ISSUE TITLE
GLFW Error and AttributeError

### ISSUE THREAD

**Issue by r-sy** [WeijingShi/Point-GNN#42]
Thank you for your open source!
When I was running the program and visualizing it：

> python3 run.py checkpoints/car_auto_T3_trainval/ --test --dataset_root_dir /home/newdisk/dataset/kitti --output_dir /home/newdisk/result/Point-GNN -l 2

 I encountered the following problem：

> Configure the viewpoint as you want and press [q]
> GLFW Error: GLX: GLX version 1.3 is required
> Failed to create window
>   0%|                                                     | 0/7518 [00:02<?, ?it/s]
> Traceback (most recent call last):
>   File "run.py", line 535, in <module>
>     custom_draw_geometry_load_option([pcd, line_set, graph_line_set])
>   File "run.py", line 532, in custom_draw_geometry_load_option
>     ctr.rotate(0.0, 3141.0, 0)
> AttributeError: 'NoneType' object has no attribute 'rotate'

If I don’t visualize, the program runs normally. How to solve this problem？
Looking forward to your reply！Best wishes！

**Comment by WeijingShi** [comment]
Hi @r-sy, Thank you very much for your interest. This error is also new to me. I tested the visualization on a fresh Ubuntu 16.04 desktop. Are you running the code on the server-side? Open3D might have issues to steam the graphics over the remote session.

**Comment by r-sy** [comment]
yes，I run the code on the server-side. I will try it on my laptop, thank you.
