### ISSUE TITLE
eval.py->def eval_repeat ()

### ISSUE THREAD

**Issue by zh9586** [WeijingShi/Point-GNN#48]
Thank you for release your great work.
I have try run python3 eval.py configs/car_auto_T3_train_eval_config 
The function falls into an endless loop.Continuous output “'Checkpoint ./checkpoints/car_auto_T3_train/model-1400001 has been evaluated already, wait for 60.000000 seconds'”.
What do you suggest？

**Comment by WeijingShi** [comment]
Hi @huihuicainiao, Thanks for your interest. The eval.py is supposed to monitor the checkpoint_dir and evaluate new checkpoints if the training produces one. You can kill it if you are not training at the same time.

**Comment by zh9586** [comment]
Thank you very much for your reply.
