### ISSUE TITLE
作者你好，我有个问题想请教下

### ISSUE THREAD

**Issue by EvaneSnow** [WeijingShi/Point-GNN#58]
1. 你放在checkpoints中的权重是使用KITTI数据集训练的吗？
2. 我还有必要使用KITTI数据集继续进行训练吗？
3. 我想对单张图片进行预测，请问如何操作？
希望得到您的回复，谢谢。

**Comment by EvaneSnow** [comment]
@WeijingShi 希望得到你的回复，谢谢

**Comment by WeijingShi** [comment]
Hi @EvaneSnow, Thanks for your interest in our work.

1. Yes, the checkpoints are all trained on KITTI.
2. Sure, you can explore better methods to re-train, fine-tuning or modify the model using KITTI data or other datasets. 
3.  We use a point cloud as input instead of an image. The easiest method to run on your own data is to organize it in KITTI format and [run the inference code](https://github.com/WeijingShi/Point-GNN/blob/2baf24f9556907f23e2e4018f1b756dac3f6c497/README.md#run-a-checkpoint):
```python3 run.py checkpoints/car_auto_T3_trainval/ --test --dataset_root_dir DATASET_ROOT_DIR --output_dir DIR_TO_SAVE_RESULTS```.

Hope it helps.

**Comment by EvaneSnow** [comment]
@WeijingShi 谢谢你的回答，我看你的用户名应该也是中国人，我就不使用英语和你交流了，抱歉哈。我是刚接触点云预测网络，偶然看到你发表在CVPR上的论文，很有兴趣。我想问哈，如果我使用这条命令进行训练：
`python3 train.py configs/car_auto_T3_train_train_config configs/car_auto_T3_train_config`
那么，我的训练类别是只有车这一类吗？能不能将车，人一起进行训练？
我在你的car_auto_T3_train_train_config文件中发现，num_classes：4，这是说明有4类车吗？
希望得到您的回复，谢谢。

**Comment by WeijingShi** [comment]
@EvaneSnow, Sure, no problem. Currently, we use separate checkpoints for cars and pedestrians, but you can try to combine them into one. The ```num_classes=4``` contains the background, side-view car, front/back-view car, and other vehicles.

**Comment by EvaneSnow** [comment]
@WeijingShi 谢谢你的回答，如果我想在前向推理过程中，看到如你论文中的三维框，二维框，
![image](https://user-images.githubusercontent.com/44998644/102841041-1cb22f00-443f-11eb-958c-8de982816975.png)

是不是需要设置`python3 run.py checkpoints/car_auto_T3_train/ --dataset_root_dir DATASET_ROOT_DIR --output_dir DIR_TO_SAVE_RESULTS --level 1`
将--level的值设置为1.

**Comment by WeijingShi** [comment]
Yes, that's correct. You can also set ```level``` to 2 to view the results one by one.

**Comment by EvaneSnow** [comment]
@WeijingShi 非常感谢你的回答，谢谢你，祝你学术事业双丰收。

**Comment by EvaneSnow** [comment]
@WeijingShi 我最后还有一个小问题，我看你论文中，前向推理，可以同时检测车，人
![image](https://user-images.githubusercontent.com/44998644/102842516-16718200-4442-11eb-8d6d-ef2d7f87dd05.png)
如果我也想在同一张点云上同时检测车，人，如何操作呢？
因为我看项目中的权重，车和人的权重参数是分开保存的，那进行权重加载时，如何进行操作？

**Comment by WeijingShi** [comment]
Hi @EvaneSnow,
The simplest way is to run two models independently on the same inputs and then put their results together. Of course, putting all classes into one network and re-train would be a better method. Best wishes to you as well!

**Comment by EvaneSnow** [comment]
真是太感谢你啦，我目前已经没有问题啦
