### ISSUE TITLE
Evaluation Results

### ISSUE THREAD

**Issue by dirk61** [WeijingShi/Point-GNN#6]
I ran eval.py on both car and ped-cyclist, the results are as followed:
![image](https://user-images.githubusercontent.com/54100411/76965608-886ee500-695f-11ea-9203-04cfd5b98cd1.png)
![image](https://user-images.githubusercontent.com/54100411/76965637-991f5b00-695f-11ea-8d1b-ec7d0d3d7c9b.png)
I wonder how can I get mAP for each difficulty level(Easy, Moderate, Hard) respectively, which is shown in Table 2. in your paper.

**Comment by WeijingShi** [comment]
The eval.py is meant to be a monitoring task for the training process. It does not output the KITTI APs.  For that, you need to use the run.py instead and use the native_kitti_evaluation tool. The [readme](../blob/master/README.md) file has the instruction on how to use them. For the test set results in Table 2, you need to submit the results to the KITTI server, as we do not have the ground truth.
