### ISSUE TITLE
Stacking layers in U-Net style

### ISSUE THREAD

**Issue by sumeshthakr** [WeijingShi/Point-GNN#68]
Hi @WeijingShi , Congratulations on your work,

I was wondering is it possible to stack GNN layers in a pyramid style using the current code base,?
or do we need to define separate skip layers?
Thank you

**Comment by WeijingShi** [comment]
Hi @sumeshthakr,  Thanks for your interest. We can use the layers in gnn.py and define an upsample graph. 

Let's say we have a point cloud **a**, and a downsampled point cloud **b**. Normally, we treat **a** as the source vertices and **b** as the destination vertices to build a graph for the pooling layer:

https://github.com/WeijingShi/Point-GNN/blob/48f3d79d5b101d3a4b8439ba74c92fcad4f7cab0/models/gnn.py#L211

We can simply use do the reversed. Use **a** as the destination and **b** as the source. It's similar to the transposed Conv op in CNN. If you want to use the same radius to generate the neighbor graph for **a** to **b** and **b** to **a**, you simply need to switch the source and destination idx in the ```edge = edge[:, 1, 0]```.

Note the models.py currently follows a downsampling order to add layers. You might need to modify it.

**Comment by sumeshthakr** [comment]
Thanks for your reply,

my only question is,
Won't we have to construct a new graph, when doing upsampling,?
Thankyou

**Comment by WeijingShi** [comment]
Hi @sumeshthakr, Not if we choose the neighbor radius of the graph to be the same. If **a** is within a distance **r** of **b**, then **b** must be within the distance **r** of **a**, right? So the graph is basically the same but the direction of edges is reversed.  But this only works when we choose the same radius in upsampling as in downsample. Otherwise, we need to construct a new graph as you suggested. Thanks,

**Comment by sumeshthakr** [comment]
Got it @WeijingShi ,

Just last query, for skip connections, do we need to define a new layer? or can we do direct concatenation?

Thankyou

**Comment by WeijingShi** [comment]
Hi @sumeshthakr  We can just add or concatenate the features of the same set of points. If the feature dims do not match, we can use an mlp to adjust. 
https://github.com/WeijingShi/Point-GNN/blob/48f3d79d5b101d3a4b8439ba74c92fcad4f7cab0/models/gnn.py#L34

**Comment by sumeshthakr** [comment]
Thanks a ton @WeijingShi ,

Yes, that totally makes sense using a MLP to concatenate features.

You said, current models.py follows a downsampling orders to add layers,
So if I want to modify it, Would I be editing configs file?

**Comment by WeijingShi** [comment]
Unfortunately, you will need to modify the models.py. The current models.py adds the layers sequentially and does not have skip connections :

https://github.com/WeijingShi/Point-GNN/blob/48f3d79d5b101d3a4b8439ba74c92fcad4f7cab0/models/models.py#L119

**Comment by sumeshthakr** [comment]
Oh,

I get it, that seems like a tricky part,

Thanks for the help
