### ISSUE TITLE
How to visualize results?

### ISSUE THREAD

**Issue by dirk61** [WeijingShi/Point-GNN#7]
In eval_config files I set "visualization to true",  then I ran eval.py, but  nothing seemed to be different. Where can I find the result outputs?

**Comment by WeijingShi** [comment]
The "visualization" in eval_config is deprecated. I plan to remove it in the future. 

For visualization, you can use the run.py script. For example:
```
python3 run.py checkpoint_path --level 1
```
This will start the non-blocking visualization.
