### ISSUE TITLE
kitti native evaluation offline output

### ISSUE THREAD

**Issue by wailok09** [WeijingShi/Point-GNN#72]
Hi Weijing,

I have installed the system packages of texlive-extra-utils, gnuplot, and ghostscript. But the output of the offline evaluation is still empty file named 'plot'. What have I done wrong? Is the 'include_directories' in cmake requires sudo access?

There are no warnings displayed, just 'done.' has shown the moment I executed the code (which is very fast)
![image](https://user-images.githubusercontent.com/74637046/108662723-e14ce300-7509-11eb-9bed-9ea3f5d4191d.png)

**Comment by jiaminglei-lei** [comment]
@wailok09  Did you finish the inference?

**Comment by wailok09** [comment]
May I ask whether the output directory is pointing to the place where I store the output of evaluation or the inference result? I'm not sure about where I shall place the inference result

**Comment by wailok09** [comment]
> @wailok09 Did you finish the inference?

I placed result_dir one more folder forward, it's successful now. Thank you.
