### ISSUE TITLE
implementing on PCAP Lidar data, and visualization

### ISSUE THREAD

**Issue by alireza1990** [WeijingShi/Point-GNN#9]
Dear WeijingShi, 

I'v been trying to implement your code on Lidar data in PCAP format. The velodyne dataset in kitti however is in binary format. It will be highly appreciated if you let me know how I can get your code to work on PCAP dataset (I was unsuccessful on converting PCAP to binary!). Furthermore, as I only have the 3D point cloud lidar data (without any RGB image for visualization) how is it possible to use the code for visualization of the bounding boxes? 

Thank you for your time and consideration.

**Comment by Juuustin** [comment]
Do you have any solutions?

**Comment by WeijingShi** [comment]
Does this parser work for you? https://github.com/ArashJavan/veloparser
At the moment, we do not have a plan to interface with Velodyne PCAP directly. 
Sorry for the late reply.
